### ISSUE TITLE
[UI] reshape product card to have a leaner more professional style

### ISSUE THREAD

**Issue by chloe4E** [chloe4E/glamgrab#26]
- what?
  work on product card styling to have a more professional style

- why?
  get away from standard MUI style

- how?
- 
![image](https://github.com/chloe4E/glamgrab/assets/31064234/8fe921d3-68be-457c-8bb3-778199fa2ff9)

**Comment by chloe4E** [comment]
colors: https://mui.com/system/palette/

**Comment by vanStaen** [comment]
Does it looks more professional though?
Or is it just a matter of tastes?

**Comment by chloe4E** [comment]
fair enough @vanStaen ;)

**Comment by vanStaen** [comment]
> fair enough @vanStaen ;)

Pity, I was hoping you would link me to a "UI best practices" or something.
